export const userDiscs = [
  {
    id: 23,
    disc: {
      id: 878,
      manufacturer: {
        id: 49,
        name: "Innova Champion Discs",
        established: 1983,
        location: "California",
        is_defunct: false,
      },
      type_display: "Putt/Approach",
      name: "Rat",
      speed: 1,
      glide: 1,
      turn: 0,
      fade: 0,
      weight: 176.0,
      type: "putt",
      diameter: 21.2,
      height: 1.7,
      rim_depth: 1.4,
      inside_rim_diameter: 18.9,
      rim_thickness: 1.1,
      rim_depth_to_diameter: 6.6,
      rim_configuration: 66.65,
      flexibility: 6.01,
      disc_class: "",
      vintage_weight: 0.0,
      plastic: "",
      color: "",
      img_url: "https://infinitediscs.com/Inf_Uploads/Disc_Images/Ratata2.JPG",
      img_alt: "innova-rat",
      final_year: null,
      cert_num: "17-77",
      approval_date: "2017-06-26",
    },
    nickname: null,
    custom_speed: null,
    custom_glide: null,
    custom_turn: null,
    custom_fade: null,
    profile: 2,
  },
  {
    id: 24,
    disc: {
      id: 1361,
      manufacturer: {
        id: 49,
        name: "Innova Champion Discs",
        established: 1983,
        location: "California",
        is_defunct: false,
      },
      type_display: "Distance Driver",
      name: "Ape",
      speed: 13,
      glide: 5,
      turn: 0,
      fade: 4,
      weight: 175.1,
      type: "dist_dr",
      diameter: 21.1,
      height: 1.5,
      rim_depth: 1.2,
      inside_rim_diameter: 16.2,
      rim_thickness: 2.4,
      rim_depth_to_diameter: 5.7,
      rim_configuration: 27.75,
      flexibility: 12.13,
      disc_class: null,
      vintage_weight: 0.0,
      plastic: null,
      color: null,
      img_url:
        "https://www.innovadiscs.com/wp-content/uploads/disc-thumbs/ape_240.jpg",
      img_alt: "innova-ape",
      final_year: null,
      cert_num: "11-04",
      approval_date: "2011-02-18",
    },
    nickname: null,
    custom_speed: null,
    custom_glide: null,
    custom_turn: null,
    custom_fade: null,
    profile: 2,
  },
  {
    id: 23,
    disc: {
      id: 878,
      manufacturer: {
        id: 49,
        name: "Innova Champion Discs",
        established: 1983,
        location: "California",
        is_defunct: false,
      },
      type_display: "Putt/Approach",
      name: "Rat",
      speed: 1,
      glide: 1,
      turn: 0,
      fade: 0,
      weight: 176.0,
      type: "putt",
      diameter: 21.2,
      height: 1.7,
      rim_depth: 1.4,
      inside_rim_diameter: 18.9,
      rim_thickness: 1.1,
      rim_depth_to_diameter: 6.6,
      rim_configuration: 66.65,
      flexibility: 6.01,
      disc_class: "",
      vintage_weight: 0.0,
      plastic: "",
      color: "",
      img_url: "https://infinitediscs.com/Inf_Uploads/Disc_Images/Ratata2.JPG",
      img_alt: "innova-rat",
      final_year: null,
      cert_num: "17-77",
      approval_date: "2017-06-26",
    },
    nickname: null,
    custom_speed: null,
    custom_glide: null,
    custom_turn: null,
    custom_fade: null,
    profile: 2,
  },
  {
    id: 24,
    disc: {
      id: 1361,
      manufacturer: {
        id: 49,
        name: "Innova Champion Discs",
        established: 1983,
        location: "California",
        is_defunct: false,
      },
      type_display: "Distance Driver",
      name: "Ape",
      speed: 13,
      glide: 5,
      turn: 0,
      fade: 4,
      weight: 175.1,
      type: "dist_dr",
      diameter: 21.1,
      height: 1.5,
      rim_depth: 1.2,
      inside_rim_diameter: 16.2,
      rim_thickness: 2.4,
      rim_depth_to_diameter: 5.7,
      rim_configuration: 27.75,
      flexibility: 12.13,
      disc_class: null,
      vintage_weight: 0.0,
      plastic: null,
      color: null,
      img_url:
        "https://www.innovadiscs.com/wp-content/uploads/disc-thumbs/ape_240.jpg",
      img_alt: "innova-ape",
      final_year: null,
      cert_num: "11-04",
      approval_date: "2011-02-18",
    },
    nickname: null,
    custom_speed: null,
    custom_glide: null,
    custom_turn: null,
    custom_fade: null,
    profile: 2,
  },
];
